mipengine/mip

- src/components/mip-carousel.js
- src/components/mip-img.js
- src/less/mip-img.less
> 修复轮播组件预览bug

- src/fixed-element.js
- src/less/mip-fixed.less
> 修复padding问题，修改高度限制为90px

- package.json
- src/components/mip-carousel.js
- src/components/mip-img.js
- src/fixed-element.js
- src/less/mip-fixed.less
- src/mip.js
- src/utils/platform.js
- src/viewer.js
> 添加platform

- package.json
- src/components/mip-carousel.js
> repair carousel

- package.json
- src/viewer.js
> change viewerjs

- package.json
- src/viewer.js
> Revert "change viewerjs"

- package.json
- src/components/mip-carousel.js
> midify mip-carousel

- karma.conf.js
- src/dom/rect.js
- src/util.js
- src/utils/fn.js
- src/utils/platform.js
- test/index.js
- test/utils/fn.js
- test/utils/platform.js
> platform扩展主流APP识别

- package.json
- src/mip.js
- src/utils/customStorage.js
> cache cookie清理

- package.json
- src/components/mip-video.js
> repair video

- package.json
- src/fixed-element.js
- test/fixed-element.js
去掉fixed元素的所有原来的限制，唯一一个限制为数量不超过10
> mip fixed去除限制

- package.json
- src/fixed-element.js
- src/less/mip-fixed.less
remove part of fixed element style limit
> remove part of fixed element style limit

- src/components/mip-pix.js
- src/components/mip-pix.md
> mip-pix 升级

- package.json
- src/dom/dom.js
- test/dom/dom.js
> 增加dom移动api

- scripts/unit/karma.unit.conf.js
build local coverage file with unit test
> build coverage file

- package.json
- scripts/unit/karma.unit.conf.js
- src/util.js
- test/util.js
modify regexp for cache module
> modify regexp

- .travis.yml
> rm saucelabs config temporary

- LICENSE
- package.json
- src/components/mip-img.js
> add webp fallback

- README-zh_CN.md
- package.json
- src/less/mip-base.less
- src/viewer.js
- test/viewer.js
> Revert "修复async加载mip.js导致的页面在ios safari不能滑动问题"

- README-zh_CN.md
- package.json
- src/less/mip-base.less
- src/viewer.js
- test/viewer.js
This reverts commit b1dc63c3cae66de8e96b896bc0e7a11f56fbca8d.
> 修复async加载mip.js导致的页面在ios safari不能滑动问题 (#207)

- package.json
- src/less/mip-base.less
> fix:解决async height问题

- README-zh_CN.md
- README.md
> fix: 修复协议徽章引用地址

- package.json
- src/utils/event-action.js
> feat: mip bind增加编译方式

- scripts/unit/karma.sauce.conf.js
- test/utils/customStorage.js
- test/viewer.js
- test/viewport.js
新增：
- anndroid 7.1
- windows10 edge
- osx firefox
- osx chrome
- ios9 safari
- ios10 safari
- ios11 safari
> feat: 添加多平台的浏览器

- src/components/mip-img.md
> docs: 修改 mip-img 文档

- src/dom/dom.js
删除 async 方案小流量代码，真 DOM ready 代码先注释下，后续肯定要用。
> chore: 下线 async 小流量代码

- src/components/mip-carousel.md
- src/components/mip-iframe.md
- src/components/mip-img.md
- src/components/mip-pix.md
- src/components/mip-video.md
> docs: 修改组件 readme

- package.json
- src/components/mip-img.js
- src/less/mip-img.less
> feat: 增加图片默认占位符

- package.json
- src/utils/fn.js
- src/viewer.js
由于 `on="tap:xx.xx"` 和页面中的点击事件会冲突，则添加一个新的事件：`on="click:xx.xx"` 事件。
fix #307
>  feat: 添加 click event action 事件
